### ISSUE TITLE
刚需！hurry 

### ISSUE THREAD

**Issue by kklod** [LaoshuBaby/waifudebt-beancount#1]

**Comment by LaoshuBaby** [comment]
有史以来最为震撼的一次，我连README都没写

不过这个项目其实就是专门用来记录抽卡氪金用的（因为我在原神、星穹铁道都有氪金，鸣潮不知道会不会氪），所以或许我应该改一下名字叫waifugacha之类的比较好（？）

希望没有对您产生误导！（鞠躬）

**Comment by kklod** [comment]
> 有史以来最为震撼的一次，我连README都没写
> 
> 不过这个项目其实就是专门用来记录抽卡氪金用的（因为我在原神、星穹铁道都有氪金，鸣潮不知道会不会氪），所以或许我应该改一下名字叫waifugacha之类的比较好（？）
> 
> 希望没有对您产生误导！（鞠躬）

额  我理解错了～～😂

**Comment by LaoshuBaby** [comment]
> 额 我理解错了～～😂

啊，那我懂了！（仿佛什么都明白了的眼神

您是想记录哪些账目是花给自己的，哪些账目是花给女友的吗？

可以在账目上添加hashtag做记录，如

```beancount
2019-01-09 * "野兽早餐" "双人份套餐（吃了吗在线优惠券）" #GirlFriend
    Assets:Card:0114        -5.14 CNY
    Assets:Chileme          -8.10 BEAN
    Expenses:Food
```

更多使用技巧推荐看看拾月老师的博客： https://www.skyue.com/19101819.html

---

~~顺带一提，如果是Waifu，一般是指二次元里的纸片人老婆，三次元的是Wife/Girlfriend~~
